### ISSUE TITLE
docker compose up fails

### ISSUE THREAD

**Issue by advatar** [netreconlab/parse-hipaa#94]
```
parse-hipaa-parse-1      | /parse-server/index.js:453
parse-hipaa-parse-1      |   const parseServer = await ParseServer.startApp(configuration);
parse-hipaa-parse-1      |                                         ^
parse-hipaa-parse-1      | 
parse-hipaa-parse-1      | TypeError: ParseServer.startApp is not a function
parse-hipaa-parse-1      |     at setupParseServer (/parse-server/index.js:453:41)
parse-hipaa-parse-1      |     at Object.<anonymous> (/parse-server/index.js:639:3)
parse-hipaa-parse-1      |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
parse-hipaa-parse-1      |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
parse-hipaa-parse-1      |     at Module.load (node:internal/modules/cjs/loader:1037:32)
parse-hipaa-parse-1      |     at Module._load (node:internal/modules/cjs/loader:878:12)
parse-hipaa-parse-1      |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
parse-hipaa-parse-1      |     at node:internal/main/run_main_module:23:47
parse-hipaa-parse-1      | 
parse-hipaa-parse-1      | Node.js v18.12.1
parse-hipaa-parse-1 exited with code 1
```

**Comment by cbaker6** [comment]
You probably have old images on your system, you should remove all images and try again. The errors you reported are from an older version of Parse Server
